version: "3"

services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "email@example.com"
      PGADMIN_DEFAULT_PASSWORD: "12345678"
    ports:
      - "16543:80"
    networks:
      - ecosystem-network

networks:
  ecosystem-network:
    driver: bridge
